"""add login_device table

Revision ID: 0752cfaa358a
Revises: 23b1d3727573
Create Date: 2026-09-24 17:10:04.467281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0752cfaa358a'
down_revision = '23b1d3727573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_login_device_user_device')
    )
    with op.batch_alter_table('login_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_device_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_device_user_id'))

    op.drop_table('login_device')
    # ### end Alembic commands ###
