"""Add questions column to quiz_challenge, make challenger_score/total_questions required

Revision ID: 094dc995b6b3
Revises: 85ec0d05a215
Create Date: 2026-09-19 21:08:31.547543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094dc995b6b3'
down_revision = '85ec0d05a215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.JSON(), nullable=False))
        batch_op.alter_column('challenger_score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_challenge', schema=None) as batch_op:
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('challenger_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('questions')

    # ### end Alembic commands ###
