"""add open_to_others to scheduled_session

Revision ID: 0f19be4e4031
Revises: b3103437bc6d
Create Date: 2026-09-21 19:18:10.942618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f19be4e4031'
down_revision = 'b3103437bc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_to_others', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_session', schema=None) as batch_op:
        batch_op.drop_column('open_to_others')

    # ### end Alembic commands ###
