"""add notification_prefs and push_subscription

Revision ID: 190e4d89fe81
Revises: 63e9596eb400
Create Date: 2026-09-21 18:21:25.230206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190e4d89fe81'
down_revision = '63e9596eb400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_prefs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_prefs')

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
