"""add question_count to quiz_set

Revision ID: 23b1d3727573
Revises: d4cb7b3275b1
Create Date: 2026-09-23 19:57:58.283261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b1d3727573'
down_revision = 'd4cb7b3275b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_count', sa.Integer(), server_default='5', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_set', schema=None) as batch_op:
        batch_op.drop_column('question_count')

    # ### end Alembic commands ###
