"""add quiz_set table

Revision ID: 2e40bc974366
Revises: e3e080d50397
Create Date: 2026-08-26 13:34:39.900128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e40bc974366'
down_revision = 'e3e080d50397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_set')
    # ### end Alembic commands ###
