"""add support message table

Revision ID: 408850cd9e6c
Revises: fe35d7cf4838
Create Date: 2026-09-08 20:13:39.795606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408850cd9e6c'
down_revision = 'fe35d7cf4838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_message')
    # ### end Alembic commands ###
