"""add password_reset_code table

Revision ID: 41f497888b4b
Revises: 0752cfaa358a
Create Date: 2026-09-24 18:52:47.686783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f497888b4b'
down_revision = '0752cfaa358a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_code_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_user_id'))

    op.drop_table('password_reset_code')
    # ### end Alembic commands ###
