"""add rating comment and feedback reasons

Revision ID: 4b08bf680b63
Revises: 85f44bc91465
Create Date: 2026-09-06 09:34:53.826892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b08bf680b63'
down_revision = '85f44bc91465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_reasons', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('feedback_reasons')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
