"""add audio_data to message

Revision ID: 558d6d612bda
Revises: dfd258c8b181
Create Date: 2026-09-10 18:56:19.538695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558d6d612bda'
down_revision = 'dfd258c8b181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('audio_data')

    # ### end Alembic commands ###
