"""add proposer_joined_at and invitee_joined_at to scheduled_session

Revision ID: 649701a1f5a9
Revises: 73b3c046c4b9
Create Date: 2026-09-22 18:42:32.129677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649701a1f5a9'
down_revision = '73b3c046c4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposer_joined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invitee_joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_session', schema=None) as batch_op:
        batch_op.drop_column('invitee_joined_at')
        batch_op.drop_column('proposer_joined_at')

    # ### end Alembic commands ###
