"""add reminder and no_show tracking to scheduled_session

Revision ID: 73b3c046c4b9
Revises: 0f19be4e4031
Create Date: 2026-09-22 18:10:27.497074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b3c046c4b9'
down_revision = '0f19be4e4031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('no_show_notified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_session', schema=None) as batch_op:
        batch_op.drop_column('no_show_notified_at')
        batch_op.drop_column('reminder_sent_at')

    # ### end Alembic commands ###
