"""make rating ratee optional, add ratee_name

Revision ID: 79b6d4297ebf
Revises: 962386db7aeb
Create Date: 2026-08-24 20:50:50.236113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b6d4297ebf'
down_revision = '962386db7aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratee_name', sa.String(length=120), nullable=True))
        batch_op.alter_column('ratee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('ratee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ratee_name')

    # ### end Alembic commands ###
