"""add session_summary table

Revision ID: 7e6177219730
Revises: f861e8091511
Create Date: 2026-08-25 21:05:17.285775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6177219730'
down_revision = 'f861e8091511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('central_topic', sa.String(length=120), nullable=False),
    sa.Column('branches', sa.JSON(), nullable=False),
    sa.Column('summary_points', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summary')
    # ### end Alembic commands ###
