"""add interested_count and interested_user_ids to help_request

Revision ID: 8bcd2093c921
Revises: 649701a1f5a9
Create Date: 2026-09-23 06:17:49.969516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcd2093c921'
down_revision = '649701a1f5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interested_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('interested_user_ids', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.drop_column('interested_user_ids')
        batch_op.drop_column('interested_count')

    # ### end Alembic commands ###
