"""add note to quiz_challenge

Revision ID: b3103437bc6d
Revises: e2e26bbe03a5
Create Date: 2026-09-21 19:10:24.053492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3103437bc6d'
down_revision = 'e2e26bbe03a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_challenge', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
