"""make quiz_challenge.challenger_score nullable

Revision ID: d4cb7b3275b1
Revises: 8bcd2093c921
Create Date: 2026-09-23 19:47:28.158120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cb7b3275b1'
down_revision = '8bcd2093c921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_challenge', schema=None) as batch_op:
        batch_op.alter_column('challenger_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_challenge', schema=None) as batch_op:
        batch_op.alter_column('challenger_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
