"""add day streak fields to user

Revision ID: decbd6b44b36
Revises: 4b08bf680b63
Create Date: 2026-09-06 09:52:00.072776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decbd6b44b36'
down_revision = '4b08bf680b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # server_default lets existing rows get a real value (0) instead
        # of failing SQLite's "can't add NOT NULL with no default" check -
        # dropped again below once every row has been backfilled.
        batch_op.add_column(sa.Column('current_streak_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('longest_streak_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_streak_date', sa.Date(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_streak_days', server_default=None)
        batch_op.alter_column('longest_streak_days', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_streak_date')
        batch_op.drop_column('longest_streak_days')
        batch_op.drop_column('current_streak_days')

    # ### end Alembic commands ###
