"""add scheduled_for to help_request

Revision ID: e2e26bbe03a5
Revises: 190e4d89fe81
Create Date: 2026-09-21 18:29:48.718988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e26bbe03a5'
down_revision = '190e4d89fe81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.drop_column('scheduled_for')

    # ### end Alembic commands ###
