"""add claimed/claimed_at to unlocked_achievement

Revision ID: f861e8091511
Revises: 05fc7aeaae02
Create Date: 2026-08-25 20:21:12.279560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f861e8091511'
down_revision = '05fc7aeaae02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlocked_achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlocked_achievement', schema=None) as batch_op:
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claimed')

    # ### end Alembic commands ###
