"""add deleted flag to message

Revision ID: fe35d7cf4838
Revises: decbd6b44b36
Create Date: 2026-09-06 10:17:29.102695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe35d7cf4838'
down_revision = 'decbd6b44b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('deleted', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
